### ISSUE TITLE
[FEAT] Open Flux Daemon port 16125

### ISSUE THREAD

**Issue by w2vy** [RunOnFlux/flux#575]
fluxd uses 16125 for inbound connections but we are not opening this port for upnp nodes
we may also want to open 16124 the rpcport

These will be 161x4 and 161x5 of course, these are set in the ~/.flux/flux.conf file
Not sure where to open an issue for multitoolbox to set flux.conf

**Comment by w2vy** [comment]
In most places we can use apiport-2 but I did notice various shell scripts that have 16125 embedded in them
I can explore this more and start the obvious work in a branch

**Comment by Meatball13** [comment]
I'd like to jump onto this enhancement request as well to request that it be possible during setup (or through changes to config after setup) to force a node to use specific ports so it's possible to run multiple Flux nodes behind a single IP by giving each of them different sets of ports to use.  I know you can do that by using UPnP, but many higher end firewalls do not allow UPnP, so that's not always an option.

**Comment by AdministratorSupportTeam** [comment]
Kindly follow the step on this link to talk to the customer care service directly on your issues anyone asking you to DM is a scam
https://direct.lc.chat/14201763/
